from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "voltra"
DEFAULT_NAME = "Beyond Power Voltra"

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.BUTTON,
    Platform.COVER,
    Platform.NUMBER,
    Platform.SELECT,
    Platform.SENSOR,
    Platform.SWITCH,
]

VOLTRA_SERVICE_UUID = "e4dada34-0867-8783-9f70-2ca29216c7e4"
VOLTRA_COMMAND_CHARACTERISTIC_UUID = "55ca1e52-7354-25de-6afc-b7df1e8816ac"
VOLTRA_NOTIFY_CHARACTERISTIC_UUID = "ca94658c-0525-5046-e78b-5391b65f47ad"
VOLTRA_TRANSPORT_CHARACTERISTIC_UUID = "a010891d-f50f-44f0-901f-9a2421a9e050"
VOLTRA_JUST_WRITE_CHARACTERISTIC_UUID = "19de84ed-0a69-482c-a8a6-c75cb5bb4389"

NOTIFY_CHARACTERISTIC_UUIDS: tuple[str, ...] = (
    VOLTRA_COMMAND_CHARACTERISTIC_UUID,
    VOLTRA_NOTIFY_CHARACTERISTIC_UUID,
    VOLTRA_TRANSPORT_CHARACTERISTIC_UUID,
)

CONFIRMED_RESPONSE_CHARACTERISTIC_UUIDS: tuple[str, ...] = (
    VOLTRA_COMMAND_CHARACTERISTIC_UUID,
    VOLTRA_TRANSPORT_CHARACTERISTIC_UUID,
)

BOOTSTRAP_WRITE_PACING_SECONDS = 0.09
PROTOCOL_RETRY_INTERVAL_SECONDS = 10.0
PERIODIC_REFRESH_INTERVAL_SECONDS = 30.0
CONNECT_RETRY_BASE_DELAY_SECONDS = 2.0
CONNECT_RETRY_MAX_DELAY_SECONDS = 30.0
